inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/**/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'with_model.gemspec'

Bundler/OrderedGems:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: false

RSpec/Be:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

Style/Documentation:
  Enabled: false
