language: ruby
sudo: false

rvm:
  - "2.6.0"
  - "2.5.3"
  - "2.4.5"
  - "2.3.8"
  - jruby-9.2.5.0

install:
  - bundle install --retry=3

env:
  - ACTIVE_RECORD_BRANCH="master"
  - ACTIVE_RECORD_VERSION="~> 5.2.0"
  - ACTIVE_RECORD_VERSION="~> 5.1.0"
  - ACTIVE_RECORD_VERSION="~> 5.0.0"
  - ACTIVE_RECORD_VERSION="~> 4.2.0"

matrix:
  fast_finish: true
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
  exclude:
    - rvm: 2.3.8
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: 2.4.5
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: jruby-9.2.5.0
      env: ACTIVE_RECORD_VERSION="~> 4.2.0"

addons:
  code_climate:
    repo_token: fe5c8a8b1b951a54707c08b6fb2a9a5edf9e0522d28bccc648454f774c9ccab1
