language: ruby

rvm:
  - "1.9"
  - "2.0"
  - "2.1"
  - jruby-19mode
  - rbx-2

install:
  - bundle install --retry=3

env:
  - ACTIVE_RECORD_BRANCH="master"
  - ACTIVE_RECORD_VERSION="~> 4.2.0"
  - ACTIVE_RECORD_VERSION="~> 4.1.0"
  - ACTIVE_RECORD_VERSION="~> 4.0.0"
  - ACTIVE_RECORD_VERSION="~> 3.2.0"
  - ACTIVE_RECORD_VERSION="~> 3.1.0"
  - ACTIVE_RECORD_VERSION="~> 3.0.0"

matrix:
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
  exclude:
    - env: ACTIVE_RECORD_BRANCH="master"
      rvm: "1.9"
    - env: ACTIVE_RECORD_BRANCH="master"
      rvm: "2.0"
    - env: ACTIVE_RECORD_BRANCH="master"
      rvm: jruby-19mode
