language: ruby

script: "bundle exec rspec spec"

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree

env:
  - ACTIVE_RECORD_VERSION="~> 4.0.0.rc1"
  - ACTIVE_RECORD_VERSION="~> 3.2.0"
  - ACTIVE_RECORD_VERSION="~> 3.1.0"
  - ACTIVE_RECORD_VERSION="~> 3.0.0"

matrix:
  allow_failures:
    - env: ACTIVE_RECORD_VERSION="~> 4.0.0.rc1"
  exclude:
    - rvm:
      - 1.8.7
      - jruby-18mode
      - rbx-18mode
      - ree
      env: ACTIVE_RECORD_VERSION="~> 4.0.0.rc1"
