language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-2.2

env:
  - ACTIVE_RECORD_BRANCH="master"
  - ACTIVE_RECORD_BRANCH="4-0-stable"
  - ACTIVE_RECORD_VERSION="~> 4.0.0"
  - ACTIVE_RECORD_VERSION="~> 3.2.0"
  - ACTIVE_RECORD_VERSION="~> 3.1.0"
  - ACTIVE_RECORD_VERSION="~> 3.0.0"

matrix:
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
    - env: ACTIVE_RECORD_BRANCH="4-0-stable"
    - rvm: jruby-19mode
      env: ACTIVE_RECORD_VERSION="~> 4.0.0"
