language: ruby
sudo: false

rvm:
  - "2.3.3"
  - "2.2.6"
  - "2.1.10"
  - jruby-9.1.6.0

install:
  - bundle install --retry=3

env:
  - ACTIVE_RECORD_BRANCH="master"
  - ACTIVE_RECORD_BRANCH="5-0-stable"
  - ACTIVE_RECORD_BRANCH="4-2-stable"
  - ACTIVE_RECORD_VERSION="~> 5.0.0"
  - ACTIVE_RECORD_VERSION="~> 4.2.0"

matrix:
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
    - env: ACTIVE_RECORD_BRANCH="5-0-stable"
    - env: ACTIVE_RECORD_BRANCH="4-2-stable"
  exclude:
    - rvm: "2.1.10"
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: "2.1.10"
      env: ACTIVE_RECORD_BRANCH="5-0-stable"
    - rvm: "2.1.10"
      env: ACTIVE_RECORD_VERSION="~> 5.0.0"
    - rvm: jruby-9.1.6.0
      env: ACTIVE_RECORD_BRANCH="master"
    - rvm: jruby-9.1.6.0
      env: ACTIVE_RECORD_BRANCH="5-0-stable"
    - rvm: jruby-9.1.6.0
      env: ACTIVE_RECORD_VERSION="~> 5.0.0"
