language: ruby
cache: bundler

rvm:
  - 3.0.0
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - jruby-9.2.13.0

env:
  global:
    - CC_TEST_REPORTER_ID=fe5c8a8b1b951a54707c08b6fb2a9a5edf9e0522d28bccc648454f774c9ccab1
  jobs:
    - ACTIVE_RECORD_BRANCH="master"
    - ACTIVE_RECORD_VERSION="~> 6.1.0"
    - ACTIVE_RECORD_VERSION="~> 6.0.0"
    - ACTIVE_RECORD_VERSION="~> 5.2.0"

jobs:
  fast_finish: true
  allow_failures:
    - env: ACTIVE_RECORD_BRANCH="master"
  exclude:
    - rvm: jruby-9.2.13.0
      env: ACTIVE_RECORD_VERSION="~> 6.0.0"
    - rvm: 3.0.0
      env: ACTIVE_RECORD_VERSION="~> 5.2.0"

before_install:
  - gem install bundler

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
