name: build

on:
  push:
    branches:
      - master
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.1', '3.2', '3.3', '3.4']
        active-record-version-env:
          - ACTIVE_RECORD_VERSION="~> 7.0.0"
          - ACTIVE_RECORD_VERSION="~> 7.1.0"
          - ACTIVE_RECORD_VERSION="~> 7.2.0"
          - ACTIVE_RECORD_VERSION="~> 8.0.0"
        allow-failure: [false]
        exclude:
          - ruby-version: '3.1'
            active-record-version-env: ACTIVE_RECORD_VERSION="~> 8.0.0"
        include:
          - ruby-version: '3.4'
            active-record-version-env: ACTIVE_RECORD_BRANCH="main"
            allow-failure: true
          - ruby-version: '3.4'
            active-record-version-env: ACTIVE_RECORD_BRANCH="8-0-stable"
            allow-failure: true
          - ruby-version: '3.4'
            active-record-version-env: ACTIVE_RECORD_BRANCH="7-2-stable"
            allow-failure: true
          - ruby-version: '3.4'
            active-record-version-env: ACTIVE_RECORD_BRANCH="7-1-stable"
            allow-failure: true
          - ruby-version: '3.4'
            active-record-version-env: ACTIVE_RECORD_BRANCH="7-0-stable"
            allow-failure: true
    continue-on-error: ${{ matrix.allow-failure }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Update bundle
      run: ${{ matrix.active-record-version-env }} bundle update
    - name: Run tests
      run: ${{ matrix.active-record-version-env }} bin/rake
